<h3>importando pandas y cargando los datasets</h3>

In [4]:
import pandas as pd

In [5]:
dfa=pd.read_csv("data/amazon_prime_titles.csv")

In [6]:
dfa.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...

In [7]:
dfd=pd.read_csv("data/disney_plus_titles.csv")
dfh=pd.read_csv("data/hulu_titles.csv")
dfn=pd.read_csv("data/netflix_titles.csv")

- Creando columna id

In [8]:
dfa["id"]="a"+dfa["show_id"]
dfd["id"]="d"+dfd["show_id"]
dfh["id"]="h"+dfh["show_id"]
dfn["id"]="n"+dfn["show_id"]

- rellenar nulos de la columna rating con G

In [9]:
dfa.rating.fillna("G",inplace=True)
dfd.rating.fillna("G",inplace=True)
dfh.rating.fillna("G",inplace=True)
dfn.rating.fillna("G",inplace=True)

- Cambiar formato de fechas

In [10]:
dfa.date_added=pd.to_datetime(dfa.date_added,infer_datetime_format=True,)
dfd.date_added=pd.to_datetime(dfd.date_added,infer_datetime_format=True)
dfh.date_added=pd.to_datetime(dfh.date_added,infer_datetime_format=True)
dfn.date_added=pd.to_datetime(dfn.date_added,infer_datetime_format=True)

- crear columnas duration_int y duration type

In [11]:
dfa[["duration_int","duration_type"]]=dfa["duration"].str.split(" ",expand=True)
dfd[["duration_int","duration_type"]]=dfd["duration"].str.split(" ",expand=True)
dfh[["duration_int","duration_type"]]=dfh["duration"].str.split(" ",expand=True)
dfn[["duration_int","duration_type"]]=dfn["duration"].str.split(" ",expand=True)
dfa.drop(columns="duration",inplace=True)
dfd.drop(columns="duration",inplace=True)
dfh.drop(columns="duration",inplace=True)
dfn.drop(columns="duration",inplace=True)

In [12]:
dfn.dtypes

show_id                  object
type                     object
title                    object
director                 object
cast                     object
country                  object
date_added       datetime64[ns]
release_year              int64
rating                   object
listed_in                object
description              object
id                       object
duration_int             object
duration_type            object
dtype: object

- Corrigiendo los tipos de datos

In [13]:
#COLUMNA duration_int en formato de dato tipo int
dfa["duration_int"]=dfa["duration_int"].astype("Int64")
dfd["duration_int"]=dfd["duration_int"].astype("Int64")
dfh["duration_int"]=dfh["duration_int"].astype("Int64")
dfn["duration_int"]=dfn["duration_int"].astype("Int64")

- Textos en minusculas

In [14]:
#amazon
dfa["title"]=dfa["title"].str.lower()
dfa["type"]=dfa["type"].str.lower()
dfa["director"]=dfa["director"].str.lower()
dfa["cast"]=dfa["cast"].str.lower()
dfa["country"]=dfa["country"].str.lower()
dfa["rating"]=dfa["rating"].str.lower()
dfa["listed_in"]=dfa["listed_in"].str.lower()
dfa["description"]=dfa["description"].str.lower()
dfa["duration_type"]=dfa["duration_type"].str.lower()
#disney
dfd["title"]=dfd["title"].str.lower()
dfd["type"]=dfd["type"].str.lower()
dfd["director"]=dfd["director"].str.lower()
dfd["cast"]=dfd["cast"].str.lower()
dfd["country"]=dfd["country"].str.lower()
dfd["rating"]=dfd["rating"].str.lower()
dfd["listed_in"]=dfd["listed_in"].str.lower()
dfd["description"]=dfd["description"].str.lower()
dfd["duration_type"]=dfd["duration_type"].str.lower()
#hulu
dfh["title"]=dfh["title"].str.lower()
dfh["type"]=dfh["type"].str.lower()
dfh["director"]=dfh["director"].str.lower()
#dfh["cast"]=dfh["cast"].str.lower()
dfh["country"]=dfh["country"].str.lower()
dfh["rating"]=dfh["rating"].str.lower()
dfh["listed_in"]=dfh["listed_in"].str.lower()
dfh["description"]=dfh["description"].str.lower()
dfh["duration_type"]=dfh["duration_type"].str.lower()
#netflix
dfn["title"]=dfn["title"].str.lower()
dfn["type"]=dfn["type"].str.lower()
dfn["director"]=dfn["director"].str.lower()
dfn["cast"]=dfn["cast"].str.lower()
dfn["country"]=dfn["country"].str.lower()
dfn["rating"]=dfn["rating"].str.lower()
dfn["listed_in"]=dfn["listed_in"].str.lower()
dfn["description"]=dfn["description"].str.lower()
dfn["duration_type"]=dfn["duration_type"].str.lower()

In [15]:
dfn.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,listed_in,description,id,duration_int,duration_type
0,s1,movie,dick johnson is dead,kirsten johnson,NaN,united states,2021-09-25,2020,pg-13,documentaries,"as her father nears the end of his life, filmm...",ns1,90,min
1,s2,tv show,blood & water,NaN,"ama qamata, khosi ngema, gail mabalane, thaban...",south africa,2021-09-24,2021,tv-ma,"international tv shows, tv dramas, tv mysteries","after crossing paths at a party, a cape town t...",ns2,2,seasons
2,s3,tv show,ganglands,julien leclercq,"sami bouajila, tracy gotoas, samuel jouy, nabi...",NaN,2021-09-24,2021,tv-ma,"crime tv shows, international tv shows, tv act...",to protect his family from a powerful drug lor...,ns3,1,season
3,s4,tv show,jailbirds new orleans,NaN,NaN,NaN,2021-09-24,2021,tv-ma,"docuseries, reality tv","feuds, flirtations and toilet talk go down amo...",ns4,1,season
4,s5,tv show,kota factory,NaN,"mayur more, jitendra kumar, ranjan raj, alam k...",india,2021-09-24,2021,tv-ma,"international tv shows, romantic tv shows, tv ...",in a city of coaching centers known to train i...,ns5,2,seasons

- Unir dataframes

In [16]:
datamov=pd.concat([dfa,dfd,dfh,dfn])

- dataframes de ratings

In [18]:
r1=pd.read_csv("data/ratings/1.csv")
r2=pd.read_csv("data/ratings/2.csv")
r3=pd.read_csv("data/ratings/3.csv")
r4=pd.read_csv("data/ratings/4.csv")
r5=pd.read_csv("data/ratings/5.csv")
r6=pd.read_csv("data/ratings/6.csv")
r7=pd.read_csv("data/ratings/7.csv")
r8=pd.read_csv("data/ratings/8.csv")

In [15]:
r1.head()

   userId  rating   timestamp movieId
0       1     1.0  1425941529   as680
1       1     4.5  1425942435  ns2186
2       1     5.0  1425941523  hs2381
3       1     5.0  1425941546  ns3663
4       1     5.0  1425941556  as9500

- Cambiar el formato de fecha y unir

In [19]:
r1['timestamp']=pd.to_datetime(r1['timestamp'],unit='s').dt.strftime('%Y-%m-%d')
r1.timestamp.astype("datetime64[ns]")
r2['timestamp']=pd.to_datetime(r2['timestamp'],unit='s').dt.strftime('%Y-%m-%d')
r2.timestamp.astype("datetime64[ns]")
r3['timestamp']=pd.to_datetime(r3['timestamp'],unit='s').dt.strftime('%Y-%m-%d')
r3.timestamp.astype("datetime64[ns]")
r4['timestamp']=pd.to_datetime(r4['timestamp'],unit='s').dt.strftime('%Y-%m-%d')
r4.timestamp.astype("datetime64[ns]")
r5['timestamp']=pd.to_datetime(r5['timestamp'],unit='s').dt.strftime('%Y-%m-%d')
r5.timestamp.astype("datetime64[ns]")
r6['timestamp']=pd.to_datetime(r6['timestamp'],unit='s').dt.strftime('%Y-%m-%d')
r6.timestamp.astype("datetime64[ns]")
r7['timestamp']=pd.to_datetime(r7['timestamp'],unit='s').dt.strftime('%Y-%m-%d')
r7.timestamp.astype("datetime64[ns]")
r8['timestamp']=pd.to_datetime(r8['timestamp'],unit='s').dt.strftime('%Y-%m-%d')
r8.timestamp.astype("datetime64[ns]")

0         2012-10-19
1         2012-10-15
2         2012-10-19
3         2012-10-15
4         2012-10-19
             ...
1499995   2007-12-04
1499996   2007-12-04
1499997   2007-12-04
1499998   2007-12-04
1499999   2007-12-04
Name: timestamp, Length: 1500000, dtype: datetime64[ns]

In [20]:
rating=pd.concat([r1,r2,r3,r4,r5,r6,r7,r8])

In [21]:
#cambiar nombre de ratings por score
rating.rename(columns={"rating":"score"},inplace=True)

In [25]:
rating.duplicated().value_counts()

False    11013823
True        10466
dtype: int64

In [27]:
rating.drop_duplicates(inplace=True)

- Obtener el promedio de los scores por cada movieId

In [20]:
df=rating.groupby(["movieId"]).score.mean().round(decimals=1)

In [21]:
#formato dataframe
df=df.to_frame()

In [22]:
df.reset_index(inplace=True)

In [23]:
df.score.value_counts()

3.5    13564
3.6     8269
3.4      976
3.7      185
3.3        4
Name: score, dtype: int64

In [24]:
df.rename(columns={"movieId":"id"},inplace=True)

<p align="center">unir dataframe de ratings con movies</p>

In [28]:
datafinal=pd.merge(datamov,df,on="id")
datafinal.rename(columns={"cast":"casting"},inplace=True)
datafinal.to_csv(path_or_buf="datfinal.csv")

In [29]:
pd.read_csv("datfinal.csv")

,Unnamed: 0,show_id,type,title,director,casting,country,date_added,release_year,rating,listed_in,description,id,duration_int,duration_type,score
0,0,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,"comedy, drama",a small fishing village must procure a local d...,as1,113.0,min,3.5
1,1,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30,2018,13+,"drama, international",a metro family decides to fight a cyber crimin...,as2,110.0,min,3.5
2,2,s3,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021-03-30,2017,g,"action, drama, suspense",after a man discovers his wife is cheating on ...,as3,74.0,min,3.5
3,3,s4,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncé, britney...",united states,2021-03-30,2014,g,documentary,"pink breaks the mold once again, bringing her ...",as4,69.0,min,3.5
4,4,s5,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,2021-03-30,1989,g,"drama, fantasy",teenage matt banting wants to work with a famo...,as5,45.0,min,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22993,22993,s8803,movie,zodiac,david fincher,"mark ruffalo, jake gyllenhaal, robert downey j...",united states,2019-11-20,2007,r,"cult movies, dramas, thrillers","a political cartoonist, a crime reporter and a...",ns8803,158.0,min,3.4
22994,22994,s8804,tv show,zombie dumb,NaN,NaN,NaN,2019-07-01,2018,tv-y7,"kids' tv, korean tv shows, tv comedies","while living alone in a spooky town, a young g...",ns8804,2.0,seasons,3.5
22995,22995,s8805,movie,zombieland,ruben fleischer,"jesse eisenberg, woody harrelson, emma stone, ...",united states,2019-11-01,2009,r,"comedies, horror movies",looking to survive in a world taken over by zo...,ns8805,88.0,min,3.4
22996,22996,s8806,movie,zoom,peter hewitt,"tim allen, courteney cox, chevy chase, kate ma...",united states,2020-01-11,2006,pg,"children & family movies, comedies","dragged from civilian life, a former superhero...",ns8806,88.0,min,3.6
22997,22997,s8807,movie,zubaan,mozez singh,"vicky kaushal, sarah-jane dias, raaghav chanan...",india,2019-03-02,2015,tv-14,"dramas, international movies, music & musicals",a scrappy but poor boy worms his way into a ty...,ns8807,111.0,min,3.5

DATASET para el sitema de recomendacion de peliculas

In [21]:
rating.rename(columns={"movieId":"id"},inplace=True)

In [23]:
dataml=pd.merge(datamov,rating,on="id")

In [25]:
dataml.to_csv("datasetml/datml.csv")

In [26]:
dataml

,show_id,type,title,director,cast,country,date_added,release_year,rating,listed_in,description,id,duration_int,duration_type,userId,score,timestamp
0,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,"comedy, drama",a small fishing village must procure a local d...,as1,113,min,543,5.0,2003-07-30
1,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,"comedy, drama",a small fishing village must procure a local d...,as1,113,min,595,3.0,1996-08-13
2,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,"comedy, drama",a small fishing village must procure a local d...,as1,113,min,611,3.0,2001-01-03
3,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,"comedy, drama",a small fishing village must procure a local d...,as1,113,min,2523,3.5,2012-06-25
4,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,"comedy, drama",a small fishing village must procure a local d...,as1,113,min,3082,4.0,2000-03-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11024284,s8807,movie,zubaan,mozez singh,"vicky kaushal, sarah-jane dias, raaghav chanan...",india,2019-03-02,2015,tv-14,"dramas, international movies, music & musicals",a scrappy but poor boy worms his way into a ty...,ns8807,111,min,122699,4.0,1999-07-17
11024285,s8807,movie,zubaan,mozez singh,"vicky kaushal, sarah-jane dias, raaghav chanan...",india,2019-03-02,2015,tv-14,"dramas, international movies, music & musicals",a scrappy but poor boy worms his way into a ty...,ns8807,111,min,122869,4.0,2015-11-11
11024286,s8807,movie,zubaan,mozez singh,"vicky kaushal, sarah-jane dias, raaghav chanan...",india,2019-03-02,2015,tv-14,"dramas, international movies, music & musicals",a scrappy but poor boy worms his way into a ty...,ns8807,111,min,123708,3.0,2001-10-12
11024287,s8807,movie,zubaan,mozez singh,"vicky kaushal, sarah-jane dias, raaghav chanan...",india,2019-03-02,2015,tv-14,"dramas, international movies, music & musicals",a scrappy but poor boy worms his way into a ty...,ns8807,111,min,123841,4.0,2001-06-01
11024288,s8807,movie,zubaan,mozez singh,"vicky kaushal, sarah-jane dias, raaghav chanan...",india,2019-03-02,2015,tv-14,"dramas, international movies, music & musicals",a scrappy but poor boy worms his way into a ty...,ns8807,111,min,124184,3.0,2000-08-18